name: Caller Workflow

on: workflow_dispatch
env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
jobs:
  use-reusable-workflow:
    uses: hung-snyk/ci-template/.github/workflows/GHA-template.yml@main  # Specify repo and branch
    # with:
    #   SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
