name: CI Workflow

on: workflow_dispatch

jobs:
  use-reusable-workflow:
    uses: hung-snyk/ci-template/.github/workflows/GHA-template.yml@main  # Specify repo and branch
    with:
      token: ${{ secrets.SNYK_TOKEN }}
